#pragma once

#include <ntddk.h>

#define KSWORD_ARK_BUGCHECK_BITMAP_MAX_BYTES (8UL * 1024UL * 1024UL)
#define KSWORD_ARK_BUGCHECK_FONT_BODY_WIDTH 10UL
#define KSWORD_ARK_BUGCHECK_FONT_BODY_HEIGHT 17UL
#define KSWORD_ARK_BUGCHECK_FONT_BODY_ADVANCE 11UL
#define KSWORD_ARK_BUGCHECK_FONT_HERO_WIDTH 20UL
#define KSWORD_ARK_BUGCHECK_FONT_HERO_HEIGHT 34UL
#define KSWORD_ARK_BUGCHECK_FONT_HERO_ADVANCE 21UL
#define KSWORD_ARK_BUGCHECK_FONT_MAX_BYTES 80750UL
